### PR TITLE
Assigned missing dismiss button function to dismiss button

### PR DESCRIPTION
**Pull request by mhansma96**
Funcionality was already available, but just not correctly linked

### CODE REVIEW

**Comment by dmundra** [comment]
Ya I shared the fix as well in #92

**Comment by shawna-slh** [comment]
Thank you @dmundra Sorry we didn't get to it until now.

**Comment by dmundra** [comment]
No worries @shawna-slh. Thanks for merging the fix.

**Comment by shawna-slh** [comment]
@mhansma96 It doesn't seem to be working?

**Comment by dmundra** [comment]
To chime in, it is working here https://deploy-preview-118--wcag-em-report-tool-2021-redesign.netlify.app/ but not here https://www.w3.org/WAI/eval/report-tool/. I think a release needs to happen to push the changes to the live app (unless I am mistaken).

**Comment by shawna-slh** [comment]
Thanks @dmundra Indeed, I forgot it was a different process than other WAI resources. And this one gave an error. I'll follow up on it soon...

**Pull request merged**
